name: "nakama"
data_dir: "/nakama/data"

logger:
  level: "DEBUG"
  stdout: true

database:
  address: "postgres:localdb@postgres:5432/nakama"

session:
  encryption_key: "default-encryption-key"
  token_expiry_sec: 7200

socket:
  server_key: "default-server-key"
  port: 7350
  max_message_size_bytes: 4096

console:
  port: 7351
  username: "admin"
  password: "password"
